dist: trusty
sudo: required

branches:
  except:
    - gh-pages
    
language:
  - cpp

compiler:
  - gcc

env:
  global:
    - GH_REPO_NAME: CXXDecomQt
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxygen/config
    - GH_REPO_REF: github.com/gabegordon/CXXDecomQt.git

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - libhdf5-serial-dev
      - libhdf5-7
      - qt*5-dev
      - build-essential
      - libgl1-mesa-dev
      - boost
script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir -p build && cd build
  - cmake ..
  - cmake --build . --target all

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
